### ISSUE TITLE
Data array is empty on Nagios Core 4.4.7

### ISSUE THREAD

**Issue by LumePart** [macskas/nagios2json#2]
Hello, I tried setting up nagios2json, but it doesn't display the data it parses, only the first few fields
![image001](https://user-images.githubusercontent.com/46826542/182798760-613dfd4d-bb64-431e-98f3-7eae203ea1f3.png)
I had it set up successfully not too long ago (1-2 months) , but unfortunately that machine got purged. Maybe I set it up differently or what could be the case?

**Comment by macskas** [comment]
Can you please send me your status.dat file? Just search & replace private data in it (hostname/servicename/etc). macskas+nagios2json AT gmail DOT com

**Comment by LumePart** [comment]
Fixed:  My problem was that every alert was in the OK status, and by default it doesn't display them. So adding servicestatustype=0 to show all alerts worked
