### ISSUE TITLE
[FEATURE REQUEST] parsing performance_data

### ISSUE THREAD

**Issue by LumePart** [macskas/nagios2json#3]
Hello again! Would it be possible to add performance_data to the json output? It would help me get even more detailed information about each host and its services.

**Comment by macskas** [comment]
&include-fields=performance_data,something_else, but this tool only showing service information. And there is no hostdata atm.

**Comment by LumePart** [comment]
Thanks a lot! And yea, I meant service data for each host, worded it a bit wrong
